Academy/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
# from mb4 import views


# from oef import views

urlpatterns = [
    # path('', views.home, name='home'),
    path('mb4/', include('mb4.urls')),
    # path('oef/', include('oef.urls')),
    path('polls/', include('polls.urls')),
    path('register/',user_views.register,name='register'),
    path('profile/',user_views.profile,name='profile'),
    path('',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
     path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.index_title = "MATHMAN ACADEMY"
admin.site.site_header = "MATHMAN ADMIN"
admin.site.site_title = "administration"

mb4/urls.py
from django.urls import path
# from .views import (
#     IndexView,
#     )
from . import views
# from django.conf.urls.static import static

# app_name = 'mb4'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:reeks_id>/', views.detail, name='detail'),
    path('training/', views.training, name='training'),
    path('resultaten/', views.resultaten, name='resultaten'),
    path('uitgewerkt/<int:opg_id>', views.uitgewerkt, name='uitgewerkt'),

    path('fav/',views.fav, name='fav'),
    path('fav/aft',views.fav_aft, name='fav_aft'),

    # path('index/', views.IndexView.as_view(), name='index'),
     # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/statististieken/', views.ResultsView.as_view(), name='statistieken'),
    # path('<int:question_id>/oefen/', views.ExcView.as_view(), name='maak_oef'),
    # # path('about/',views.about, name='oef-about'),

    # path('add/',views.add, name='add'),
    # # path('2F2F/',views.toofast, name='2F2F'),
    # path('2F2F/77',views.toofast77, name='2F2F_77'),
    # path('fav/',views.fav, name='fav'),
    # path('fav/aft',views.fav_aft, name='fav_aft'),
    # path('',views.home, name='oef-home'),
    # # path('ingelogd/',views.ingelogd, name='ingelogd'),
    # # path('',PostListView.as_view(), name='oef-home'),
    # path('oef/',PostListView.as_view(), name='oef-home'),
    # path('user/<str:username>',UserPostListView.as_view(), name='user-posts'),
    # path('post/<int:pk>/',PostDetailView.as_view(), name='post-detail'),
    # path('post/new/',PostCreateView.as_view(), name='post-create'),
    # path('post/<int:pk>/update/',PostUpdateView.as_view(), name='post-update'),
    # path('post/<int:pk>/delete/',PostDeleteView.as_view(), name='post-delete'),

]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/resultaten/', views.ResultsView.as_view(), name='resultaten'),
    path('<int:question_id>/stem/', views.vote, name='stem'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Je hebt geen keuze geselecteerd.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:resultaten', args=(question.id,)))

polls/templates/polls/detail.html
<form action="{% url 'polls:stem' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Stem">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">



Hallo jij! Je bent op de Mathman Academy nu!
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Momenteel zijn er geen polls.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Nog eens stemmen?</a>

polls/templates/polls/vulin.html
{% extends "mb4/base.html" %}



{% block content %}
<br>
<br>
<br>
{% if request.user.is_authenticated %}





<form action="{% url 'vulin' reeks.id %}" method="post">

{% csrf_token %}
<fieldset>
    <legend><h1>{{ reeks.titel }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <li>
            <img class ="opgave" src="/media/vragen/vraag%20{{ index  }}.png" alt="Vraag" width="60%" height="12%">
            <br>
            <br>
            <input type="textinput" name="opgave" id="opgave{{ index }}" value="">
            <!-- <label type="textinput" for="opgave{{ forloop.counter }}">{{ opgave.onderwerp }}</label><br> -->
            <br>
        </li>
<!--         <input type="radio" name="opgave" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
 -->
</fieldset>
<br>
<br>

<input class="btn-primary " type="submit" value="Stem">
</form>


{% else %}
        Je bent nog niet ingelogd!
{% endif %}

<br>
<br><br>
<br>
<br><br>
<br>
<br><br>
<br>
<br>
{% endblock content %}